version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet restore
      - run:
          name: "Run Application Tests"
          command: dotnet test
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application"
          command: dotnet build
  publish:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Publish Application"
          command: dotnet publish
workflows:
  build-and-test:
    jobs:
      - test
      - build:
          requires:
            - test
      - publish:
          requires:
            - test
            - build
          filters:
            branch:
              only:
                - master
