version: 2.1

orbs:
  windows: circleci/windows@2.2.0
  cloudfoundry: circleci/cloudfoundry@0.1.73

jobs:
  test:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet restore
      - run:
          name: "Run Application Tests"
          command: dotnet test
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application"
          command: dotnet build
  publish:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Publish Application"
          command: dotnet publish
      - run:
          name: "Copy manifest to publish folder"
          command: cp manifest.yml .\EA.UsageTracking.Application.API\bin\Debug\netcoreapp3.1\publish\
      - run:
          name: "Go to Publish folder"
          command: cd EA.UsageTracking.Application.API\bin\Debug\netcoreapp3.1\publish\
  deploy:
    executor:
      name: windows/default
    steps:
      - run:
          name: "Deploy"
          command: echo Deploy
workflows:
  build_deploy:
    jobs:
      - cloudfoundry/blue_green:
          appname: ea-usage-tracking
          build_steps:
            - test
            - build:
              requires:
                - test
            - publish:
              requires:
                - test
                - build
              filters:
                branches:
                  only:
                    - master
          context: govuk-paas-sandbox
          domain: your-domain
          manifest: null
          org: dof-dss
          space: sandbox
          validate_steps:
            - run: echo 'your validation steps'
            - run: echo 'you can also have more of these'

