version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  test:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Run Application Tests"
          command: dotnet test
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application"
          command: dotnet build
workflows:
  build-and-test:
    jobs:
      - test
      - build:
          requires:
            - test