version: 2.1

orbs:
  windows: circleci/windows@2.2.0
  cloudfoundry: circleci/cloudfoundry@0.1.73

commands:
  install_cmd:
    parameters:
      org:
        type: string
        default: "DOF-DSS"
      space:
        type: string
        default: "sandbox"
    steps:
      - run:
          command: |
            Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
            choco install cloudfoundry-cli
            cf -v
            cf api https://api.london.cloud.service.gov.uk
            cf auth "$CF_USERNAME" "$CF_PASSWORD"
            cf target
            echo "$CF_SPACE" 
            cf target -o << parameters.org >>  -s << parameters.space >> 

jobs:
  test:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Install project dependencies"
          command: dotnet restore
      - run:
          name: "Run Application Tests"
          command: dotnet test
  build:
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Build Application"
          command: dotnet build
  publish:
    parameters:
      manifest:
        type: string
    executor:
      name: windows/default
    steps:
      - checkout
      - run:
          name: "Publish Application"
          command: dotnet publish
      - run: | 
          cd EA.UsageTracking.Application.API
          cp << parameters.manifest >> bin\Debug\netcoreapp3.1\publish
      - persist_to_workspace:
          root: EA.UsageTracking.Application.API\bin\Debug\netcoreapp3.1
          paths:
            - publish
  deploy:
    parameters:
      space:
        type: string
    executor:
      name: windows/default
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp
      - install_cmd:
          org: "DOF-DSS"
          space: << parameters.space >>
      - run: |
          cd tmp/publish
          cf push
workflows:
  build-and-test-and-deploy-sandbox:
    jobs:
      - test
      - build:
          requires:
            - test
      - publish:
          manifest: "manifest.sandbox.yml"
          requires:
            - test
            - build
          filters:
            branches:
              only:
                - master
      - deploy:
          space: "sandbox"
          requires:
            - publish
          context: govuk-paas-sandbox
  build-and-test-and-deploy-staging:
    jobs:
      - test:
          filters:    # selected tags and no branches
            tags:
              only: /^v(0|[0-9]\d*)\.(0|[0-9]\d*)\.(0|[0-9]\d*)(?:-(alpha|beta))?$/
            branches:
              ignore: /.*/
      - build:
          requires:
            - test
          filters:    # selected tags and no branches
            tags:
              only: /^v(0|[0-9]\d*)\.(0|[0-9]\d*)\.(0|[0-9]\d*)(?:-(alpha|beta))?$/
            branches:
              ignore: /.*/
      - publish:
          manifest: "manifest.staging.yml"
          requires:
            - test
            - build
          filters:    # selected tags and no branches
            tags:
              only: /^v(0|[0-9]\d*)\.(0|[0-9]\d*)\.(0|[0-9]\d*)(?:-(alpha|beta))?$/
            branches:
              ignore: /.*/
      - deploy:
          space: "staging"
          requires:
            - publish
          context: govuk-paas-staging

